### ISSUE TITLE
fb comments is down for some url

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/minet#222]
```
Scraping comments: 156154 comments [23:25:29,  1.30s/ comments, calls=1, posts=4908, q=1, replies=0]Traceback (most recent call last):
  File "minet/cli/__main__.py", line 236, in <module>
  File "minet/cli/__main__.py", line 215, in main
  File "minet/cli/facebook/__init__.py", line 14, in facebook_action
  File "minet/cli/facebook/comments.py", line 75, in facebook_comments_action
  File "minet/facebook/mobile_scraper.py", line 244, in comments
  File "minet/facebook/mobile_scraper.py", line 143, in scrape_comments
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by Yomguithereal** [comment]
The faulty url is: https://www.facebook.com/groups/1812604535522746/permalink/1826017657514767

**Comment by Yomguithereal** [comment]
This post is not available anymore. Cannot reproduce.
