### ISSUE TITLE
[minet twitter friends] "Missing required parameter: grant_type"

### ISSUE THREAD

**Issue by bmaz** [medialab/minet#299]
Traceback (most recent call last):
  File "/home/bma/.pyenv/versions/minet/bin/minet", line 10, in <module>
    sys.exit(main())
  File "/home/bma/.pyenv/versions/3.8.0/envs/minet/lib/python3.8/site-packages/minet/cli/__main__.py", line 215, in main
    fn(args)
  File "/home/bma/.pyenv/versions/3.8.0/envs/minet/lib/python3.8/site-packages/minet/cli/twitter/__init__.py", line 47, in twitter_action
    twitter_friends_action(namespace, output_file)
  File "/home/bma/.pyenv/versions/3.8.0/envs/minet/lib/python3.8/site-packages/minet/cli/twitter/utils.py", line 23, in action
    wrapper = TwitterWrapper(
  File "/home/bma/.pyenv/versions/3.8.0/envs/minet/lib/python3.8/site-packages/twitwi/client_wrapper.py", line 48, in __init__
    bearer_token_client.oauth2.token(grant_type='client_credentials')
  File "/home/bma/.pyenv/versions/3.8.0/envs/minet/lib/python3.8/site-packages/twitter/api.py", line 334, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "/home/bma/.pyenv/versions/3.8.0/envs/minet/lib/python3.8/site-packages/twitter/api.py", line 367, in _handle_response
    raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 403 for URL: oauth2/token using parameters: (grant_type=client_credentials)
details: {"errors":[{"code":170,"message":"Missing required parameter: grant_type","label":"forbidden_missing_parameter"}]}

**Comment by boogheta** [comment]
Shall be fixed by using twitter1.19
