### ISSUE TITLE
_csv.Error: field larger than field limit (131072)

### ISSUE THREAD

**Issue by dsottimano** [medialab/minet#326]
Is there a quick workaround here to bypass the csv field limit? 

command used: `minet fetch https://edition.cnn.com | minet extract > extracted.csv`
system: mac OS 

```
(base) ➜  work minet fetch https://edition.cnn.com | minet extract > extracted.csv
Fetching pages: 1 urls [00:00,  1.12 urls/s, errors=0]
Traceback (most recent call last):
  File "/Users/admin/opt/anaconda3/bin/minet", line 8, in <module>
    sys.exit(main())
  File "/Users/admin/opt/anaconda3/lib/python3.8/site-packages/minet/cli/__main__.py", line 209, in main
    fn(cli_args)
  File "/Users/admin/opt/anaconda3/lib/python3.8/site-packages/minet/cli/extract.py", line 161, in extract_action
    for error, row, result in pool.imap_unordered(worker, files):
  File "/Users/admin/opt/anaconda3/lib/python3.8/site-packages/minet/multiprocessing.py", line 68, in imap_unordered
    yield from self.inner_pool.imap_unordered(WorkerWrapper(worker), tasks)
  File "/Users/admin/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
_csv.Error: field larger than field limit (131072)
Extracting content: 0 docs [00:01, ? docs/s, p=8]
```

**Comment by Yomguithereal** [comment]
Hello @dsottimano. That's quite weird since the csv field size limit is already set at the maximum supported by your OS, in principles. This is done here: https://github.com/medialab/minet/blob/master/minet/cli/__main__.py#L239 `131072` seems very low. Are you using the standalone, or the pip version?

**Comment by Yomguithereal** [comment]
ping @dsottimano
