### ISSUE TITLE
User-tweets error

### ISSUE THREAD

**Issue by metinefendie** [medialab/minet#376]
While using "twitter user-tweets" function, Minet sometimes crushes and responds the error given below. Is it because of the python package I am using?

"Retrieving tweets: 33406 tweets [04:10, 152.87 tweets/s, calls=289, done=76, errors=6, user=isimzorisim]Traceback (most recent call last): File "/Users/omermetin/opt/anaconda3/lib/python3.9/site-packages/twitter/api.py", line 393, in _handle_response
    res = json.loads(data.decode('utf8'))
  File "/Users/omermetin/opt/anaconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/omermetin/opt/anaconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/omermetin/opt/anaconda3/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 652053 (char 652052)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omermetin/opt/anaconda3/bin/minet", line 8, in <module>
    sys.exit(main())
  File "/Users/omermetin/opt/anaconda3/lib/python3.9/site-packages/minet/cli/__main__.py", line 218, in main
    fn(cli_args)
  File "/Users/omermetin/opt/anaconda3/lib/python3.9/site-packages/minet/cli/twitter/__init__.py", line 56, in twitter_action
    twitter_user_tweets_action(cli_args)
  File "/Users/omermetin/opt/anaconda3/lib/python3.9/site-packages/minet/cli/twitter/user_tweets.py", line 63, in twitter_user_tweets_action
    tweets = wrapper.call(['statuses', 'user_timeline'], **kwargs)
  File "/Users/omermetin/opt/anaconda3/lib/python3.9/site-packages/twitwi/client_wrapper.py", line 79, in call
    return self.endpoints[auth].__getattr__(route)(**kwargs)
  File "/Users/omermetin/opt/anaconda3/lib/python3.9/site-packages/twitter/api.py", line 364, in __call__
    return self._handle_response(req, uri, arg_data, _timeout)
  File "/Users/omermetin/opt/anaconda3/lib/python3.9/site-packages/twitter/api.py", line 397, in _handle_response
    raise TwitterError("Incomplete JSON data collected for %s (%s): %s)" % (uri, arg_data, e))
twitter.api.TwitterError: Incomplete JSON data collected for 1.1/statuses/user_timeline (count=200&include_rts=True&max_id=979655510755553279&oauth_consumer_key=hXx0CiJG2TRa2ZnlQ2fuoXkZT&oauth_nonce=16152815157129075120&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1638982080&oauth_token=2945094669-Z0lkCxhSUcxbenHTZYA5mHZVGIegkqtDpDDFoTu&oauth_version=1.0&screen_name=isimzorisim&tweet_mode=extended&oauth_signature=p0EyRSrtguiEGT32UmlQj4xFvjM%3D): Unterminated string starting at: line 1 column 652053 (char 652052))
Retrieving tweets: 33406 tweets [04:17, 129.76 tweets/s, calls=289, done=76, errors=6, user=isimzorisim]"

**Comment by Yomguithereal** [comment]
Hello @metinefendie,

Usually this can happen if you have a bad Internet connexion or if Twitter has server issues on their own. But I remember having implemented safeguards to recover from those problems automatically. Can you tell me which version of minet you are running (`minet --version`)?

**Comment by Yomguithereal** [comment]
@metinefendie I have just released a v0.56.1 that should increase stability of the command for this kind of case but I am afraid it has everything to do with connexion quality and/or Twitter issues.

@boogheta do you recognize this kind of problem? How do we handle that on gazouilloire?

**Comment by metinefendie** [comment]
I was using minet v0.52.13 . The reason I was using v0.52.13 was that gazouilloire v1.0.1 requires minet<v0.53 . Thanks a lot! I will try v0.56.1 anyways. 

> Hello @metinefendie,
> 
> Usually this can happen if you have a bad Internet connexion or if Twitter has server issues on their own. But I remember having implemented safeguards to recover from those problems automatically. Can you tell me which version of minet you are running (`minet --version`)?
