### ISSUE TITLE
Encoding error when scraping Twitter under Windows

### ISSUE THREAD

**Issue by boogheta** [medialab/minet#379]
```
C:\Users\dane\Downloads\windows>minet twitter scrape tweets "#continuitepedagogique" --limit 20 > tweets.csv
Searching for "#continuitepedagogique"
Collecting tweets: 5%|█▏ | 1/20 [00:01<00:25, 1.36s/tweet, queries=1, tokens=1]Traceback (most recent call last):
File "minet\cli\__main__.py", line 254, in <module>
File "minet\cli\__main__.py", line 218, in main
File "minet\cli\twitter\__init__.py", line 31, in twitter_action
File "minet\cli\twitter\scrape.py", line 73, in twitter_scrape_action
File "casanova\enricher.py", line 139, in writerow
File "tqdm\contrib\__init__.py", line 29, in write
File "tqdm\std.py", line 619, in write
File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u30fc' in position 162: character maps to <undefined>
[30300] Failed to execute script __main__
```

**Comment by Yomguithereal** [comment]
Unfortunately this cannot really be fixed in windows but it can be worked around using `-o` rather than `>`.
