### ISSUE TITLE
Another quenouille stack

### ISSUE THREAD

**Issue by boogheta** [medialab/minet#47]
Not sure how we got there:
```
Exception in thread Thread-3325:
Traceback (most recent call last):
  File "/home/boo/.pyenv/versions/3.6.9/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/boo/.pyenv/versions/3.6.9/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/quenouille/imap.py", line 323, in worker
    enqueue(job)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/quenouille/imap.py", line 235, in enqueue
    assert current_group is not None
AssertionError
```

**Comment by boogheta** [comment]
Oups I got it again
