### ISSUE TITLE
Encoding error while running commands on Windows without -o

### ISSUE THREAD

**Issue by boogheta** [medialab/minet#497]
The solution is probably just to add -o and avoid stdout, but maybe we could either encode stdout in cp1252 under windows, or always yell at the user when he's not using -o under that OS

Once when running instagram hashtag:

```PS C:\Users\install\Downloads\windows> .\minet.exe instagram hashtag jemenbatsleclito -c 'INSTAGRAMCOOKIE'
query,id,media_type,shortcode,url,caption,hashtags,mentioned_names,liked_by_count,comments_disabled,comment_count,preview_like_count,video_view_count,owner_id,taken_at_timestamp,utc_
time,accessibility_caption,display_url
.\minet.exe :
Au caractère Ligne:1 : 1
+ .\minet.exe instagram hashtag jemenbatsleclito -c 'mid=Y1p19wALAAEhtO ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Retrieving posts: 0 hashtags [00:00, ? hashtags/s]Traceback (most recent call last):
  File "minet\cli\__main__.py", line 252, in <module>
  File "minet\cli\__main__.py", line 215, in main
  File "minet\cli\instagram\__init__.py", line 15, in instagram_action
  File "minet\cli\instagram\hashtag.py", line 34, in hashtag_action
  File "casanova\enricher.py", line 129, in writerow
  File "tqdm\contrib\__init__.py", line 29, in write
  File "tqdm\std.py", line 619, in write
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f449' in position 114: character maps to <undefined>
[17448] Failed to execute script '__main__' due to unhandled exception!```

Also when running fetch:

```PS D:\Programmes\minet> ./minet.exe fetch display_url l214insta.csv
query,id,media_type,shortcode,url,caption,hashtags,mentioned_names,liked_by_count,comments_disabled,comment_count,preview_like_count,video_view_count,owner_id,taken
_at_timestamp,utc_time,accessibility_caption,display_url,index,resolved,status,error,filename,mimetype,encoding
./minet.exe :
Au caractère Ligne:1 : 1
+ ./minet.exe fetch display_url l214insta.csv
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Fetching pages:   0%|          | 0/140 [00:00<?, ?url/s]
Fetching pages:   0%|          | 0/140 [00:01<?, ?url/s, errors=0]
Fetching pages:   1%|          | 1/140 [00:01<04:07,  1.78s/url, errors=0]
Fetching pages:   1%|          | 1/140 [00:01<04:09,  1.80s/url, errors=0]
Traceback (most recent call last):
  File "minet\cli\__main__.py", line 252, in <module>
  File "minet\cli\__main__.py", line 215, in main
  File "ebbe\decorators.py", line 29, in wrapped
  File "minet\cli\fetch.py", line 356, in fetch_action
  File "minet\cli\fetch.py", line 290, in write_fetch_output
  File "casanova\enricher.py", line 160, in writerow
  File "casanova\enricher.py", line 129, in writerow
  File "tqdm\contrib\__init__.py", line 29, in write
  File "tqdm\std.py", line 619, in write
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 90-91: character maps to <undefined>
[12572] Failed to execute script '__main__' due to unhandled exception!```

**Comment by Tyrannas** [comment]
+1 on this, having the same error

apparently using `sys.stdout.reconfigure(encoding='utf-8')`should work to fix this without using the -o trick

**Comment by Yomguithereal** [comment]
I am not entirely convinced `sys.stdout.reconfigure(encoding='utf-8')` would not break something else quite frankly. @Tyrannas I don't have a windows machine on hand. Would you be willing to test this on your end on the default Windows shell (i.e. not Powershell) and report whether it works when the command outputs non-ascii chars?

**Comment by Tyrannas** [comment]
Yes it's working on windows on cmd, here is the command I tried:

`minet tiktok search-videos test-l 1 > test.csv`

a possibility could be to change the sys.stdtout only on windows with a sys.platform check

(and for the record I put the "fix" in minet.__init__.py)

**Comment by Yomguithereal** [comment]
@Tyrannas can you review https://github.com/medialab/minet/commit/91fdd5df5482e4e24ac6e6bee5fcaf6d2f81f545?
