### ISSUE TITLE
Another encoding stack

### ISSUE THREAD

**Issue by boogheta** [medialab/minet#54]
```
Traceback (most recent call last):
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/urllib3/response.py", line 362, in _decode
    data = self._decoder.decompress(data)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/urllib3/response.py", line 82, in decompress
    ret += self._obj.decompress(data)
zlib.error: Error -3 while decompressing data: incorrect header check

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/complete_links_resolving_v2.py", line 115, in <module>
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "bin/complete_links_resolving_v2.py", line 66, in resolve
    for res in multithreaded_resolve(urls_to_clear, threads=min(50, batch_size), throttle=0.2, max_redirects=10, follow_meta_refresh=True):
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/quenouille/imap.py", line 381, in output
    raise e.with_traceback(trace)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/quenouille/imap.py", line 316, in worker
    result = func(data)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/minet/fetch.py", line 258, in worker
    **kwargs)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/minet/utils.py", line 310, in resolve
    chunk = response.read(1024)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/urllib3/response.py", line 503, in read
    data = self._decode(data, decode_content, flush_decoder)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/urllib3/response.py", line 367, in _decode
    "failed to decode it." % content_encoding, e)
urllib3.exceptions.DecodeError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check',))

```

**Comment by boogheta** [comment]
New one:
```
Traceback (most recent call last):
  File "bin/complete_links_resolving_v2.py", line 118, in <module>
    resolve()
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "bin/complete_links_resolving_v2.py", line 81, in resolve
    raise e
  File "bin/complete_links_resolving_v2.py", line 67, in resolve
    for res in multithreaded_resolve(urls_to_clear, threads=min(50, batch_size), throttle=0.2, max_redirects=10, follow_meta_refresh=True):
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/quenouille/imap.py", line 381, in output
    raise e.with_traceback(trace)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/quenouille/imap.py", line 316, in worker
    result = func(data)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/minet/fetch.py", line 258, in worker
    **kwargs)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/minet/utils.py", line 274, in resolve
    spoof_ua=spoof_ua
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/minet/utils.py", line 219, in request
    retries=False
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/urllib3/poolmanager.py", line 315, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/urllib3/poolmanager.py", line 231, in connection_from_host
    return self.connection_from_context(request_context)
  File "/home/boo/.pyenv/versions/quenouille/lib/python3.6/site-packages/urllib3/poolmanager.py", line 241, in connection_from_context
    pool_key_constructor = self.key_fn_by_scheme[scheme]
KeyError: 'ttps'
```
