### ISSUE TITLE
Error on fetching images from csv

### ISSUE THREAD

**Issue by lakonis** [medialab/minet#665]
Hello, I cannot explain the following error when reproducing [your doc twitter_images](https://github.com/medialab/minet/blob/master/docs/cookbook/twitter_images.md)

`minet fetch: error: argument file: single argument is expected to be a valid url! Got "media_urls"`

Here is the command line I am using : `minet fetch media_urls -i ./csv/mycsv.csv   --explode "|"   -O ./images/mycsv   --throttle 0   --domain-parallelism 5`

I used `minet scrap` to collect tweets, then filtered the tweets containing image (using Pandas). The csv seems all clean and it does contain the column `media_urls`.
Here are the first 10 lines:

```csv
,id,timestamp_utc,local_time,user_screen_name,text,possibly_sensitive,retweet_count,like_count,reply_count,impression_count,lang,to_username,to_userid,to_tweetid,source_name,source_url,user_location,lat,lng,user_id,user_name,user_verified,user_description,user_url,user_image,user_tweets,user_followers,user_friends,user_likes,user_lists,user_created_at,user_timestamp_utc,collected_via,match_query,retweeted_id,retweeted_user,retweeted_user_id,retweeted_timestamp_utc,quoted_id,quoted_user,quoted_user_id,quoted_timestamp_utc,collection_time,url,place_country_code,place_name,place_type,place_coordinates,links,domains,media_urls,media_files,media_types,media_alt_texts,mentioned_names,mentioned_ids,hashtags,intervention_type,intervention_text,intervention_url
7,806122066219069442,1481029452,2016-12-06T13:04:12,athanorster,1955 #MarilynMonroe monte sa maison de production avec Milton Greene (qui prend la photo) https://twitter.com/athanorster/status/806122066219069442/photo/1,0.0,0,0,0,,fr,,,,Twitter Web Client,http://twitter.com,Paris,,,18504485,Anne Savelli,0,"Ecrire + @lairnu et Bruits https://t.co/Mqg7JI3yrv. Le nouveau : Musée Marilyn, éd. Inculte, août 2022.",http://annesavelli.fr/,https://pbs.twimg.com/profile_images/1330459626765234179/V3ORVpws_normal.jpg,25422,2826,963,5909,103,2008-12-31T11:26:23,1230722783,scraping,1,,,,,,,,,2023-02-15T17:43:23.293725,https://twitter.com/athanorster/status/806122066219069442,,,,,,,https://pbs.twimg.com/media/Cy_rk6WW8AAk1wN.jpg,806122066219069442_Cy_rk6WW8AAk1wN.jpg,photo,,,,marilynmonroe,,,
8,804660616719896576,1480681015,2016-12-02T12:16:55,athanorster,Un peu de #MarilynMonroe dans l'exposition de Richard Avedon à @laBnF https://twitter.com/athanorster/status/804660616719896576/photo/1,0.0,0,2,0,,fr,,,,Twitter for iPad,http://twitter.com/#!/download/ipad,Paris,,,18504485,Anne Savelli,0,"Ecrire + @lairnu et Bruits https://t.co/Mqg7JI3yrv. Le nouveau : Musée Marilyn, éd. Inculte, août 2022.",http://annesavelli.fr/,https://pbs.twimg.com/profile_images/1330459626765234179/V3ORVpws_normal.jpg,25422,2826,963,5909,103,2008-12-31T11:26:23,1230722783,scraping,1,,,,,,,,,2023-02-15T17:43:23.293999,https://twitter.com/athanorster/status/804660616719896576,,,,,,,https://pbs.twimg.com/media/Cyq6j54XEAASu85.jpg,804660616719896576_Cyq6j54XEAASu85.jpg,photo,,labnf,857691266,marilynmonroe,,,
10,766569169873670144,1471599306,2016-08-19T09:35:06,athanorster,"Marilyn, série ""chocolats"" (John Florea, 1953) #MarilynMonroe https://twitter.com/athanorster/status/766569169873670144/photo/1",0.0,0,1,0,,pt,,,,Twitter Web Client,http://twitter.com,Paris,,,18504485,Anne Savelli,0,"Ecrire + @lairnu et Bruits https://t.co/Mqg7JI3yrv. Le nouveau : Musée Marilyn, éd. Inculte, août 2022.",http://annesavelli.fr/,https://pbs.twimg.com/profile_images/1330459626765234179/V3ORVpws_normal.jpg,25422,2826,963,5909,103,2008-12-31T11:26:23,1230722783,scraping,1,,,,,,,,,2023-02-15T17:43:23.294577,https://twitter.com/athanorster/status/766569169873670144,,,,,,,https://pbs.twimg.com/media/CqNmdQTWcAA3jl6.jpg,766569169873670144_CqNmdQTWcAA3jl6.jpg,photo,,,,marilynmonroe,,,
16,724615481198534657,1461596768,2016-04-25T15:06:08,athanorster,"http://fenetresopenspace.blogspot.fr/2016/04/apparition.html (apparition de #MarilynMonroe, aussi) https://twitter.com/athanorster/status/724615481198534657/photo/1",0.0,2,3,0,,fr,,,,Twitter Web Client,http://twitter.com,Paris,,,18504485,Anne Savelli,0,"Ecrire + @lairnu et Bruits https://t.co/Mqg7JI3yrv. Le nouveau : Musée Marilyn, éd. Inculte, août 2022.",http://annesavelli.fr/,https://pbs.twimg.com/profile_images/1330459626765234179/V3ORVpws_normal.jpg,25422,2826,963,5909,103,2008-12-31T11:26:23,1230722783,scraping,1,,,,,,,,,2023-02-15T17:43:23.296937,https://twitter.com/athanorster/status/724615481198534657,,,,,http://fenetresopenspace.blogspot.fr/2016/04/apparition.html,fenetresopenspace.blogspot.fr,https://pbs.twimg.com/media/Cg5Z8HfW0AAuDYz.jpg,724615481198534657_Cg5Z8HfW0AAuDYz.jpg,photo,,,,marilynmonroe,,,
```

What can be wrong ?

**Comment by Yomguithereal** [comment]
@lakonis I think you are using an outdated version of minet wrt the commands described in the cookbook document you indicate.

Can you upgrade minet? If you installed using pip, just run the following:

```bash
pip install minet==1.0.0a3
```

else if you installed the standalone version re-run this:

```bash
curl -sSL https://raw.githubusercontent.com/medialab/minet/master/scripts/install.sh | bash
```

**Comment by lakonis** [comment]
before:
```bash
> minet --version
minet 0.67.1
```

after:
```bash
> minet --version
minet 1.0.0-a3 (2023-03-03)

```

I run minet, without `explode` option :
```bash
> minet fetch media_urls -i ./images/images-marilynatlarge.csv -O ./images/marilynatlarge --throttle 0 --domain-parallelism 5 
Traceback (most recent call last):
  File "/home/nicolas/.local/bin/minet", line 8, in <module>
    sys.exit(main())
  File "/home/nicolas/.local/lib/python3.10/site-packages/minet/cli/__main__.py", line 14, in main
    run("minet", "%s (%s)" % (__version__, __published__), MINET_COMMANDS)
  File "/home/nicolas/.local/lib/python3.10/site-packages/minet/cli/utils.py", line 44, in wrapper
    fn(*args, **kwargs)
  File "/home/nicolas/.local/lib/python3.10/site-packages/minet/cli/run.py", line 101, in run
    m = importlib.import_module(meta["package"])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicolas/.local/lib/python3.10/site-packages/minet/cli/fetch/fetch.py", line 14, in <module>
    from minet.fetch import (
  File "/home/nicolas/.local/lib/python3.10/site-packages/minet/fetch.py", line 302, in <module>
    class HTTPThreadPoolExecutor(ThreadPoolExecutor[ItemType, Optional[str], ResultType]):
TypeError: 'type' object is not subscriptable

**Comment by Yomguithereal** [comment]
@lakonis your snippet indicates `1.0.0-a3` it should be `1.0.0-a13` (sorry this is on me, I wrote the version number wrong in my first reply).

**Comment by lakonis** [comment]
It works :+1:  

thanks for reactivity :rocket:
