### ISSUE TITLE
No handling of "unknown encoding" errors

### ISSUE THREAD

**Issue by sally14** [medialab/minet#73]
While using `minet extract report.csv > articles.csv` , there is no handling of "unknown encoding" errors, causing the script to crash with the following traceback : 

```
Extracting content: 4201 docs [00:26, 145.57 docs/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/salome/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/salome/miniconda3/lib/python3.7/site-packages/minet/cli/extract.py", line 40, in worker
    with codecs.open(path, 'r', encoding=encoding, errors='replace') as f:
  File "/home/salome/miniconda3/lib/python3.7/codecs.py", line 901, in open
    info = lookup(encoding)
LookupError: unknown encoding: utf-8859-1
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/salome/miniconda3/bin/minet", line 10, in <module>
    sys.exit(main())
  File "/home/salome/miniconda3/lib/python3.7/site-packages/minet/cli/__main__.py", line 187, in main
    fn(args)
  File "/home/salome/miniconda3/lib/python3.7/site-packages/minet/cli/extract.py", line 86, in extract_action
    for error, line, content in pool.imap_unordered(worker, files):
  File "/home/salome/miniconda3/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
LookupError: unknown encoding: utf-8859-1

```

It would be great if the event was caught with only a warning, and the corrupted file skipped.

Thank you!

**Comment by Yomguithereal** [comment]
There is also an issue for the `fetch` command. @boogheta what do you think we should do by default (i.e. when we don't standardize everything to utf-8), should we yield an unknown encoding error? Or should we try to be more clever?

**Comment by sally14** [comment]
URL that would trigger the encoding error :
https://www.environnementdurable.net/

Its encoding appears as utf-8859-1 in report.csv

**Comment by boogheta** [comment]
I guess when encountering a non existing encoding, we could try/except to decode with a few canonical encodings such as iso-8859-1, utf-8 and windows-1252 (maybe outputting also a warning message) and yield an unknown encoding error only if none of these work.
For the CLI, having an option to enable/disable failOnError could be useful. Not sure what the default behavior should be though
