### ISSUE TITLE
extract: TrafilaturaError not catched

### ISSUE THREAD

**Issue by bmaz** [medialab/minet#777]
"""
Traceback (most recent call last):
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/extraction.py", line 73, in extract
    trafilatura_bare_result = bare_extraction(text)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/trafilatura/core.py", line 880, in bare_extraction
    document = extract_metadata(tree, url, date_extraction_params, no_fallback, author_blacklist)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/trafilatura/metadata.py", line 439, in extract_metadata
    metadata = extract_meta_json(tree, metadata)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/trafilatura/metadata.py", line 111, in extract_meta_json
    metadata = extract_json(schema, metadata)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/trafilatura/json_metadata.py", line 84, in extract_json
    metadata.author = normalize_authors(metadata.author, author_name)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/trafilatura/utils.py", line 316, in normalize_authors
    if author_string.lower().startswith('http') or AUTHOR_EMAIL.match(author_string):
AttributeError: 'dict' object has no attribute 'lower'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bmazoyer/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/multiprocessing.py", line 36, in __call__
    return self.fn(*args, **kwargs)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/cli/extract/extract.py", line 58, in worker
    result.data = extract(text)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/extraction.py", line 75, in extract
    raise TrafilaturaError(reason=e)
minet.exceptions.TrafilaturaError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bmazoyer/.pyenv/versions/minet/bin/minet", line 8, in <module>
    sys.exit(main())
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/cli/__main__.py", line 14, in main
    run("minet", __identifier__, MINET_COMMANDS)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/cli/utils.py", line 49, in wrapper
    fn(*args, **kwargs)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/cli/run.py", line 119, in run
    fn(cli_args)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/cli/utils.py", line 427, in wrapper
    return action(cli_args, *args, **additional_kwargs, **kwargs)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/cli/extract/extract.py", line 116, in action
    for result in pool.imap_unordered(
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/multiprocessing.py", line 66, in imap_unordered
    yield from self.inner_pool.imap_unordered(
  File "/home/bmazoyer/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/pool.py", line 865, in next
    raise value
minet.exceptions.TrafilaturaError

**Comment by bmaz** [comment]
reproduce : minet fetch https://www.nationalgeographic.fr/animaux/ces-requins-blancs-comptent-parmi-les-plus-grands-du-monde | minet extract -i -

**Comment by bmaz** [comment]
It seems that an update to trafilatura 1.6 solves this issue but I did not test it extensively.
