### ISSUE TITLE
[extract] UnicodeEncodeError

### ISSUE THREAD

**Issue by bmaz** [medialab/minet#778]
Traceback (most recent call last):
  File "/home/bmazoyer/.pyenv/versions/minet/bin/minet", line 8, in <module>
    sys.exit(main())
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/cli/__main__.py", line 14, in main
    run("minet", __identifier__, MINET_COMMANDS)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/cli/utils.py", line 49, in wrapper
    fn(*args, **kwargs)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/cli/run.py", line 119, in run
    fn(cli_args)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/cli/utils.py", line 427, in wrapper
    return action(cli_args, *args, **additional_kwargs, **kwargs)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/cli/extract/extract.py", line 165, in action
    enricher.writerow(item.index, row, [None], data)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/casanova/enricher.py", line 228, in writerow
    super().writerow(row, [index], add, *addenda)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/casanova/enricher.py", line 184, in writerow
    self.writer.writerow(self.__formatrow(row, add, *addenda))
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/casanova/writer.py", line 149, in writerow
    self.__writerow(row)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/casanova/writer.py", line 124, in <lambda>
    self.__writerow = lambda row: self.__writer.writerow(
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 2903-2906: surrogates not allowed

**Comment by bmaz** [comment]
http://traveltomorrow.com/traditional-and-classical-music-from-kazakhstan-to-hit-brussels/

**Comment by Yomguithereal** [comment]
First issue: casanova should strip null bytes post row-coercion.

**Comment by Yomguithereal** [comment]
This said, this is probably an error from trafilatura extraction because this should not be able to arrive naturally without decoding with `surrogatepass`

**Comment by Yomguithereal** [comment]
Will fix surrogate issues on trafilatura metadata as per solution here: https://stackoverflow.com/questions/38147259/how-can-i-convert-surrogate-pairs-to-normal-string-in-python
