### ISSUE TITLE
[extract] CouldNotInferEncodingError

### ISSUE THREAD

**Issue by bmaz** [medialab/minet#779]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/bmazoyer/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/multiprocessing.py", line 36, in __call__
    return self.fn(*args, **kwargs)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/cli/extract/extract.py", line 51, in worker
    text = read_potentially_gzipped_path(
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/fs.py", line 43, in read_potentially_gzipped_path
    raise CouldNotInferEncodingError
minet.exceptions.CouldNotInferEncodingError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bmazoyer/.pyenv/versions/minet/bin/minet", line 8, in <module>
    sys.exit(main())
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/cli/__main__.py", line 14, in main
    run("minet", __identifier__, MINET_COMMANDS)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/cli/utils.py", line 49, in wrapper
    fn(*args, **kwargs)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/cli/run.py", line 119, in run
    fn(cli_args)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/cli/utils.py", line 427, in wrapper
    return action(cli_args, *args, **additional_kwargs, **kwargs)
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/cli/extract/extract.py", line 121, in action
    for result in pool.imap_unordered(
  File "/home/bmazoyer/.pyenv/versions/3.8.2/envs/minet/lib/python3.8/site-packages/minet/multiprocessing.py", line 66, in imap_unordered
    yield from self.inner_pool.imap_unordered(
  File "/home/bmazoyer/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/pool.py", line 865, in next
    raise value
minet.exceptions.CouldNotInferEncodingError

**Comment by Yomguithereal** [comment]
Tu as une url que je puisse reproduire?

**Comment by bmaz** [comment]
minet fetch http://traveltomorrow.com/traditional-and-classical-music-from-kazakhstan-to-hit-brussels/ | minet extract -i -

**Comment by Yomguithereal** [comment]
Note to self: we might want to add a fallback encoding to extract & scrape

**Comment by bmaz** [comment]
https://cultinfos.com/buzz/1009770-un-guide-film-de-vacances-a-television-2022-un-programme-complet
