### ISSUE TITLE
Issues (core dump or cannot unpack non-iterable FocusCrawlInfo object)

### ISSUE THREAD

**Issue by TeaS0710** [medialab/minet#977]
Hello, I encounter issues with minet focus-crawl when I try to execute these commands I encounter these issues, I use linux kubuntu, and I also tried with windows 10 and I encounter the same errors. (my minet version is minet 2.0.4 (2024-05-28))

**issues 1 (resume):** 
Segmentation fault (core dumped)

**issue 2 (resume):** 
minet process was stopped because an error occurred!
Traceback (most recent call last):
  File "/home/teas/.local/lib/python3.12/site-packages/minet/crawl/crawler.py", line 222, in __call__
    data, next_jobs = spider_result
    ^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable FocusCrawlInfo object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/teas/.local/bin/minet", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/teas/.local/lib/python3.12/site-packages/minet/cli/__main__.py", line 14, in main
    run("minet", __identifier__, MINET_COMMANDS)
  File "/home/teas/.local/lib/python3.12/site-packages/minet/cli/utils.py", line 49, in wrapper
    fn(*args, **kwargs)
  File "/home/teas/.local/lib/python3.12/site-packages/minet/cli/run.py", line 139, in run
    fn(cli_args)
  File "/home/teas/.local/lib/python3.12/site-packages/minet/cli/crawl/focus.py", line 41, in action
    return crawl_action(
           ^^^^^^^^^^^^^
  File "/home/teas/.local/lib/python3.12/site-packages/ebbe/decorators.py", line 38, in wrapped
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/teas/.local/lib/python3.12/site-packages/minet/cli/utils.py", line 356, in wrapper
    return action(cli_args, *args, **additional_kwargs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teas/.local/lib/python3.12/site-packages/minet/cli/utils.py", line 478, in wrapper
    fn(cli_args, loading_bar=loading_bar, **kwargs)
  File "/home/teas/.local/lib/python3.12/site-packages/minet/cli/crawl/crawl.py", line 356, in crawl_action
    for result, result_path in crawler.crawl(callback=callback):
  File "/home/teas/.local/lib/python3.12/site-packages/minet/crawl/crawler.py", line 587, in crawl
    for item in imap_unordered:
  File "/home/teas/.local/lib/python3.12/site-packages/quenouille/imap.py", line 1055, in output
    raise job.exc_info[1].with_traceback(job.exc_info[2])  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teas/.local/lib/python3.12/site-packages/quenouille/imap.py", line 95, in __call__
    self.result = self.func(self.item)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/teas/.local/lib/python3.12/site-packages/minet/crawl/crawler.py", line 224, in __call__
    raise TypeError(
TypeError: Spider.process is expected to return either None or a 2-tuple containing data and next targets to enqueue. Got a "FocusCrawlInfo" instead.

**first issue (full):**
minet focus-crawl https://solidaires-etudiant-e-s.org/site/ -O SOLcrawl -U ^https:\/\/solidaires-etudiant-e-s\.org\/site\/.*$ --domain-parallelism 1500 --spoof-user-agent --throttle 0
Crawling ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━   822/1,928 pages ⠧ [ 43%] in 34.22s (24.02/s eta: 11.00s)                                                
queued 1,098 doing 8 done 822 relevant 782 irrelevant 40                                                                                                    Segmentation fault (core dumped)

**second issue (full):** 
minet focus-crawl https://solidaires-etudiant-e-s.org/site/ -O SOLcrawl -U ^https:\/\/solidaires-etudiant-e-s\.org\/site\/.*$ --domain-parallelism 1500 --spoof-user-agent --throttle 0 -k
Crawling ━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   350/1,323 pages ⠙ [ 26%] in 11.29s (30.99/s eta: 5.00s)                                                 
queued 964 doing 2 done 357 relevant 342 irrelevant 8                                                                                                       
minet process was stopped because an error occurred!
Traceback (most recent call last):
  File "/home/teas/.local/lib/python3.12/site-packages/minet/crawl/crawler.py", line 222, in __call__
    data, next_jobs = spider_result
    ^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable FocusCrawlInfo object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/teas/.local/bin/minet", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/teas/.local/lib/python3.12/site-packages/minet/cli/__main__.py", line 14, in main
    run("minet", __identifier__, MINET_COMMANDS)
  File "/home/teas/.local/lib/python3.12/site-packages/minet/cli/utils.py", line 49, in wrapper
    fn(*args, **kwargs)
  File "/home/teas/.local/lib/python3.12/site-packages/minet/cli/run.py", line 139, in run
    fn(cli_args)
  File "/home/teas/.local/lib/python3.12/site-packages/minet/cli/crawl/focus.py", line 41, in action
    return crawl_action(
           ^^^^^^^^^^^^^
  File "/home/teas/.local/lib/python3.12/site-packages/ebbe/decorators.py", line 38, in wrapped
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/teas/.local/lib/python3.12/site-packages/minet/cli/utils.py", line 356, in wrapper
    return action(cli_args, *args, **additional_kwargs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teas/.local/lib/python3.12/site-packages/minet/cli/utils.py", line 478, in wrapper
    fn(cli_args, loading_bar=loading_bar, **kwargs)
  File "/home/teas/.local/lib/python3.12/site-packages/minet/cli/crawl/crawl.py", line 356, in crawl_action
    for result, result_path in crawler.crawl(callback=callback):
  File "/home/teas/.local/lib/python3.12/site-packages/minet/crawl/crawler.py", line 587, in crawl
    for item in imap_unordered:
  File "/home/teas/.local/lib/python3.12/site-packages/quenouille/imap.py", line 1055, in output
    raise job.exc_info[1].with_traceback(job.exc_info[2])  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/teas/.local/lib/python3.12/site-packages/quenouille/imap.py", line 95, in __call__
    self.result = self.func(self.item)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/teas/.local/lib/python3.12/site-packages/minet/crawl/crawler.py", line 224, in __call__
    raise TypeError(
TypeError: Spider.process is expected to return either None or a 2-tuple containing data and next targets to enqueue. Got a "FocusCrawlInfo" instead.

**third issue (full):**
minet focus-crawl https://solidaires-etudiant-e-s.org/site/ -O SOLcrawl -U ^https:\/\/solidaires-etudiant-e-s\.org\/site\/.*$ --domain-parallelism 1500 --spoof-user-agent --throttle 0 -k
Crawling ━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━   876/2,004 pages ⠼ [ 44%] in 38.79s (22.58/s eta: 1:08.0)                                                
queued 1,120 doing 8 done 876 relevant 838 irrelevant 38                                                                                                    Segmentation fault (core dumped)

**Comment by Yomguithereal** [comment]
@TeaS0710 just publshed a fix that should take care of this issue. The fix is available from v2.0.5. Can you test it and tell me whether this fits the bill?
